name: Autofix

on:
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  autofix:
    needs: setup
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Lint
        run: pnpm --recursive --fix

      - name: Format
        run: pnpm --recursive format

      - uses: autofix-ci/action@v1
