name: Build and Test

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build_and_test:
    needs: setup
    runs-on: self-hosted
    steps:
      - name: Test
        run: pnpm --recursive test:unit

      - name: Build
        run: pnpm --recursive build
